### PR TITLE
Execution handler upgrade to PowerShell3

### PR DESCRIPTION
**Pull request by jvilimek**
Fix for issue #14 .
Simply upgrade execution handler to PowerShell3.
Hope this will fix the warning.
How can I test the changes?

### CODE REVIEW

**Comment by jvilimek** [comment]
@sebastianlux  ? can you comment please?

**Comment by jvilimek** [comment]
Any update? Dead project?

**Comment by Bouke** [comment]
I'm running into the same warning on our CI pipeline as well. Hopefully @sebastianlux is able to publish a new release, I'm very grateful for this task!

**Comment by Banner-Keith** [comment]
I would consider creating a fork of this project and pushing it to the store. The MIT license is pretty permissive and @sebastianlux doesn't show any github activity for a couple of years now.

**Comment by interrubke** [comment]
Yes, please make a fork of it, as this takes way to long..

**Comment by cbiegner** [comment]
Last comment is quite old but anyway. Is there an official branch as mentioned in the last comment?

**Comment by jvilimek** [comment]
Hi @cbiegner. Unfortunately I am off the project that originally needed this. I see no other forks and I am not able to maintain Oriflame's fork, so I will close the PR for now as unresolved. Sorry for that.

**Pull request closed without merging**
